# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-16 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Nome:')),
                ('sub_titulo', models.CharField(max_length=150, verbose_name='Sub Titulo:')),
                ('img', models.ImageField(blank=True, upload_to='corretor/static/img/cat', verbose_name='Insira uma imagem')),
            ],
        ),
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome*:')),
                ('nasc', models.DateField(verbose_name='Data de nascimento*:')),
                ('cpf', models.CharField(max_length=16, verbose_name='Cpf:')),
                ('creci', models.CharField(max_length=12, verbose_name='Creci Físico*:')),
                ('telefone', models.CharField(blank=True, max_length=16, verbose_name='Telefone:')),
                ('phone', models.CharField(max_length=16, verbose_name='Celular:')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail*:')),
                ('site', models.URLField(blank=True, verbose_name='site')),
                ('endereco', models.CharField(max_length=254, verbose_name='Endereço *:')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro*:')),
                ('cidade', models.CharField(max_length=200, verbose_name='Cidade*:')),
                ('cep', models.CharField(blank=True, max_length=16, verbose_name=' Cep*:')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('São Paulo', 'SP'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=100, verbose_name='Estado*:')),
                ('ativacao', models.CharField(blank=True, choices=[('1', 'Inativo'), ('2', 'Ativo')], default=1, max_length=10)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
            ],
            options={
                'verbose_name': 'Corretore',
            },
        ),
        migrations.CreateModel(
            name='CorretorAfiliado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome: * ')),
                ('nasc', models.DateField(verbose_name='Data de nascimento')),
                ('cpf', models.CharField(max_length=16, verbose_name='CPF: * ')),
                ('creci', models.CharField(max_length=12, verbose_name=' Creci Físico: * ')),
                ('telefone', models.CharField(max_length=16, verbose_name='Telefone:*')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Celular: * ')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail *: ')),
                ('endereco', models.CharField(max_length=254, verbose_name='Endereço *:')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro*:')),
                ('cidade', models.CharField(max_length=200, verbose_name='Cidade*:')),
                ('cep', models.CharField(blank=True, max_length=16, verbose_name=' Cep*:')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('São Paulo', 'SP'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=100, verbose_name='Estado*:')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
            ],
        ),
        migrations.CreateModel(
            name='Empreendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Nome:(campo obrigatório)')),
                ('sub_titulo', models.CharField(max_length=150, verbose_name='Sub titulo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('img', models.ImageField(blank=True, upload_to='static/img/empreendimento', verbose_name='Insira uma imagem:')),
                ('lancamento', models.DateField(blank=True, null=True, verbose_name='Data prevista para lançamento')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('São Paulo', 'SP'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=100, verbose_name='Estado: (campo obrigatório)')),
                ('status', models.CharField(choices=[('1', 'Pronto para Construir'), ('2', 'Em breve'), ('3', 'Lançado')], max_length=30, verbose_name='Status')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canal_corretor.Categoria', verbose_name='categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do arquivo')),
                ('img', models.ImageField(blank=True, upload_to='static/img/mt', verbose_name='Insira uma imagem')),
                ('ep_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canal_corretor.Empreendimento')),
            ],
        ),
        migrations.CreateModel(
            name='Imobiliaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='static/img/imob', verbose_name='Insira uma imagem:')),
                ('razao', models.CharField(max_length=200, verbose_name=' Razão social  *:')),
                ('creci_j', models.CharField(max_length=6, verbose_name='Creci Jurídico *:')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Fantasia *:')),
                ('cnpj', models.CharField(max_length=14, verbose_name=' Cnpj *:')),
                ('endereco', models.CharField(max_length=254, verbose_name='Endereço *:')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro *: ')),
                ('cidade', models.CharField(max_length=200, verbose_name='Cidade *: ')),
                ('cep', models.CharField(max_length=12, verbose_name=' Cep *: ')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('São Paulo', 'SP'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=100, verbose_name='Estado*:')),
                ('telefone', models.CharField(blank=True, max_length=16, verbose_name='Telefone:')),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Celular: ')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail *:')),
                ('site', models.URLField(blank=True, verbose_name='site')),
                ('resp', models.CharField(max_length=150, verbose_name='Corretor Resposável*:')),
                ('email_resp', models.CharField(max_length=200, verbose_name='Email do Responsável:')),
                ('cpf', models.CharField(max_length=16, verbose_name='CPF *: ')),
                ('creci_f', models.CharField(blank=True, max_length=12, verbose_name=' Creci Físico *: ')),
                ('ativacao', models.CharField(blank=True, choices=[('1', 'Inativo'), ('2', 'Ativo')], default=1, max_length=10)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do arquivo')),
                ('img', models.ImageField(blank=True, upload_to='static/img/ma', verbose_name='Insira uma imagem')),
                ('ep_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canal_corretor.Empreendimento')),
            ],
            options={
                'verbose_name': 'Material de apoio',
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do arquivo')),
                ('file', models.FileField(blank=True, upload_to='static/doc', verbose_name='Arquivos ')),
                ('ep_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canal_corretor.Empreendimento')),
            ],
        ),
        migrations.CreateModel(
            name='Tabela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do arquivo')),
                ('file', models.FileField(blank=True, upload_to='static/doc', verbose_name='Arquivos ')),
                ('ep_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canal_corretor.Empreendimento')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iframe', models.CharField(max_length=250, verbose_name='Insira iframe')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do arquivo')),
                ('ep_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canal_corretor.Empreendimento')),
            ],
        ),
        migrations.AddField(
            model_name='corretorafiliado',
            name='id_imob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canal_corretor.Imobiliaria'),
        ),
    ]
