# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imobiliaria',
            name='cpf',
            field=models.CharField(max_length=16, verbose_name='Cep: (Campo obrigatório)'),
        ),
    ]
