# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canal_corretor.Categoria', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='material',
            name='img',
            field=models.ImageField(blank=True, upload_to=None, verbose_name='Insira uma imagem'),
        ),
    ]
