# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autonomo',
            name='status',
            field=models.CharField(choices=[('1', 'Inativo'), ('2', 'Ativo')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='autonomo',
            name='bairro',
            field=models.CharField(max_length=100, verbose_name='Bairro*:'),
        ),
        migrations.AlterField(
            model_name='autonomo',
            name='cep',
            field=models.CharField(max_length=16, verbose_name=' Cep*:'),
        ),
        migrations.AlterField(
            model_name='autonomo',
            name='cidade',
            field=models.CharField(max_length=200, verbose_name='Cidade*:'),
        ),
        migrations.AlterField(
            model_name='autonomo',
            name='cpf',
            field=models.CharField(max_length=16, verbose_name='Cpf:'),
        ),
        migrations.AlterField(
            model_name='autonomo',
            name='creci',
            field=models.CharField(max_length=12, verbose_name='Creci Físico*:'),
        ),
        migrations.AlterField(
            model_name='autonomo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail*:'),
        ),
        migrations.AlterField(
            model_name='autonomo',
            name='endereco',
            field=models.CharField(max_length=254, verbose_name='Endereço *:'),
        ),
        migrations.AlterField(
            model_name='autonomo',
            name='estado',
            field=models.CharField(choices=[('Acre', 'AC'), ('Alagoas', 'AL'), ('Amapá', 'AP'), ('Amazonas', 'AM'), ('Bahia', 'BA'), ('Ceará', 'CE'), ('Distrito Federal', 'DF'), ('Espírito Santo', 'ES'), ('Goiás', 'GO'), ('Maranhão', 'MA'), ('Mato Grosso', 'MT'), ('Mato Grosso do Sul', 'MS'), ('Minas Gerais', 'MG'), ('Pará', 'PA'), ('Paraíba', 'PB'), ('Paraná', 'PR'), ('Pernambuco', 'PE'), ('Piauí', 'PI'), ('Rio de Janeiro', 'RJ'), ('Rio Grande do Norte', 'RN'), ('Rio Grande do Sul', 'RS'), ('Rondônia', 'RO'), ('Roraima', 'RR'), ('Santa Catarina', 'SC'), ('São Paulo', 'SP'), ('Sergipe', 'SE'), ('Tocantins', 'TO')], max_length=10, verbose_name='Estado*:'),
        ),
        migrations.AlterField(
            model_name='autonomo',
            name='nasc',
            field=models.DateField(verbose_name='Data de nascimento*:'),
        ),
        migrations.AlterField(
            model_name='autonomo',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome*:'),
        ),
        migrations.AlterField(
            model_name='autonomo',
            name='phone',
            field=models.CharField(blank=True, max_length=16, verbose_name='Celular:'),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='cpf',
            field=models.CharField(max_length=16, verbose_name='CPF: * '),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='creci',
            field=models.CharField(max_length=12, verbose_name=' Creci Físico: * '),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail *: '),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome: * '),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='phone',
            field=models.CharField(blank=True, max_length=16, verbose_name='Celular: * '),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='telefone',
            field=models.CharField(max_length=16, verbose_name='Telefone:*'),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro *: '),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='cep',
            field=models.CharField(max_length=12, verbose_name=' Cep *: '),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='cidade',
            field=models.CharField(max_length=200, verbose_name='Cidade *: '),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='cnpj',
            field=models.CharField(max_length=14, verbose_name=' Cnpj *:'),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='cpf',
            field=models.CharField(max_length=16, verbose_name='CPF *: '),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='creci_f',
            field=models.CharField(max_length=12, verbose_name=' Creci Físico *: '),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='creci_j',
            field=models.CharField(max_length=6, verbose_name='Creci Jurídico *:'),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail *:'),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='endereco',
            field=models.CharField(max_length=254, verbose_name='Endereço *:'),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome Fantasia *:'),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='razao',
            field=models.CharField(max_length=200, verbose_name=' Razão social  *:'),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='resp',
            field=models.CharField(max_length=150, verbose_name='Corretor Resposável *:'),
        ),
    ]
