# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-24 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corretor',
            name='user',
        ),
    ]
