# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corretor',
            options={'verbose_name': 'Corretore'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='img',
            field=models.ImageField(blank=True, upload_to='/static/img/cat', verbose_name='Insira uma imagem'),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='cep',
            field=models.CharField(max_length=16, verbose_name=' Cep*:'),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='cep',
            field=models.CharField(max_length=12, verbose_name=' Cep *: '),
        ),
    ]
