# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-14 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0002_auto_20161013_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='url',
        ),
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, upload_to=None, verbose_name='Link para arquivos de texto'),
        ),
    ]
