# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0002_remove_corretor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='creci',
            field=models.CharField(blank=True, max_length=12, verbose_name=' Creci Físico: * '),
        ),
        migrations.AlterField(
            model_name='prova',
            name='resposta',
            field=models.CharField(blank=True, choices=[('1', 'a'), ('2', 'b'), ('3', 'c'), ('4', 'd')], max_length=5, verbose_name='Resposta Correta'),
        ),
    ]
