# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0003_empreendimento_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretor',
            name='cep',
            field=models.IntegerField(max_length=8, verbose_name='Digite somente numeros:'),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='phone',
            field=models.IntegerField(max_length=14, verbose_name='Digite somente numeros:'),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='img',
            field=models.ImageField(blank=True, height_field='374', upload_to=None, width_field='1024'),
        ),
    ]
