# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0004_auto_20161013_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='img',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
