# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-14 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0004_auto_20161014_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='descricao',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
