# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-05 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0004_pagina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imobiliaria',
            name='cnpj',
            field=models.CharField(max_length=30, verbose_name=' Cnpj *:'),
        ),
    ]
