# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-14 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0005_auto_20161014_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Nome:'),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='cidade',
            field=models.CharField(default='none', max_length=200, verbose_name='Cidade: (campo obrigatório)'),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='creci',
            field=models.IntegerField(verbose_name='Registro CRECI: (campo obrigatório)'),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail: (campo obrigatório)'),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='endereco',
            field=models.CharField(max_length=254, verbose_name='Endereço:(campo obrigatório)'),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='estado',
            field=models.CharField(choices=[('Acre', 'AC'), ('Alagoas', 'AL'), ('Amapá', 'AP'), ('Amazonas', 'AM'), ('Bahia', 'BA'), ('Ceará', 'CE'), ('Distrito Federal', 'DF'), ('Espírito Santo', 'ES'), ('Goiás', 'GO'), ('Maranhão', 'MA'), ('Mato Grosso', 'MT'), ('Mato Grosso do Sul', 'MS'), ('Minas Gerais', 'MG'), ('Pará', 'PA'), ('Paraíba', 'PB'), ('Paraná', 'PR'), ('Pernambuco', 'PE'), ('Piauí', 'PI'), ('Rio de Janeiro', 'RJ'), ('Rio Grande do Norte', 'RN'), ('Rio Grande do Sul', 'RS'), ('Rondônia', 'RO'), ('Roraima', 'RR'), ('Santa Catarina', 'SC'), ('São Paulo', 'SP'), ('Sergipe', 'SE'), ('Tocantins', 'TO')], max_length=100, verbose_name='Estado: (campo obrigatório)'),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='phone',
            field=models.IntegerField(verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='lancamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data prevista para lançamento'),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Nome:(campo obrigatório)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, upload_to=None, verbose_name='Arquivos texto'),
        ),
        migrations.AlterField(
            model_name='material',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome: (campo obrigatório)'),
        ),
    ]
