# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-05 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0005_auto_20170105_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretor',
            name='nome',
            field=models.CharField(help_text='Preencha o campo nome.', max_length=150, verbose_name='Nome*:'),
        ),
    ]
