# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0005_auto_20161013_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretor',
            name='cep',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='endereco',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
