# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-12 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0006_auto_20170105_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='ep_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planta', to='canal_corretor.Empreendimento'),
        ),
    ]
