# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0006_auto_20161024_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autonomo',
            name='status',
        ),
        migrations.AddField(
            model_name='autonomo',
            name='ativacao',
            field=models.CharField(blank=True, choices=[('1', 'Inativo'), ('2', 'Ativo')], default='Inativo', max_length=10),
        ),
    ]
