# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-14 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0006_auto_20161014_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretor',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome: (campo obrigatório)'),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='phone',
            field=models.IntegerField(max_length=14, verbose_name='Telefone: (campo obrigatório)'),
        ),
    ]
