# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-14 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0007_auto_20161014_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='corretor',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Jurídica', 'J'), ('Fisica', 'F')], max_length=10, verbose_name='Tipo registro:'),
        ),
        migrations.AlterField(
            model_name='corretor',
            name='phone',
            field=models.IntegerField(verbose_name='Telefone: (campo obrigatório)'),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='estado',
            field=models.CharField(blank=True, choices=[('Acre', 'AC'), ('Alagoas', 'AL'), ('Amapá', 'AP'), ('Amazonas', 'AM'), ('Bahia', 'BA'), ('Ceará', 'CE'), ('Distrito Federal', 'DF'), ('Espírito Santo', 'ES'), ('Goiás', 'GO'), ('Maranhão', 'MA'), ('Mato Grosso', 'MT'), ('Mato Grosso do Sul', 'MS'), ('Minas Gerais', 'MG'), ('Pará', 'PA'), ('Paraíba', 'PB'), ('Paraná', 'PR'), ('Pernambuco', 'PE'), ('Piauí', 'PI'), ('Rio de Janeiro', 'RJ'), ('Rio Grande do Norte', 'RN'), ('Rio Grande do Sul', 'RS'), ('Rondônia', 'RO'), ('Roraima', 'RR'), ('Santa Catarina', 'SC'), ('São Paulo', 'SP'), ('Sergipe', 'SE'), ('Tocantins', 'TO')], max_length=100, verbose_name='Estado: (campo obrigatório)'),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='img',
            field=models.ImageField(blank=True, upload_to=None, verbose_name='Insira uma imagem:'),
        ),
    ]
