# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0007_material'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Corretor',
            new_name='Corretore',
        ),
    ]
