# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0007_auto_20161024_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autonomo',
            name='ativacao',
            field=models.CharField(blank=True, choices=[('Inativo', '1'), ('Ativo', '2')], default='Inativo', max_length=10),
        ),
    ]
