# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0008_auto_20161013_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='id_em',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.PROTECT, to='canal_corretor.Empreendimento'),
            preserve_default=False,
        ),
    ]
