# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-18 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0008_auto_20161014_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corretor',
            name='author',
        ),
        migrations.AlterField(
            model_name='corretor',
            name='tipo',
            field=models.CharField(blank=True, choices=[('J', 'Jurídica'), ('F', 'Fisica')], max_length=10, verbose_name='Tipo registro:'),
        ),
    ]
