# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-13 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0008_auto_20170113_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='ep_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video', to='canal_corretor.Empreendimento'),
        ),
    ]
