# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0008_auto_20161024_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='corretor',
            name='ativacao',
            field=models.CharField(blank=True, choices=[('1', 'Inativo'), ('2', 'Ativo')], default='Inativo', max_length=10),
        ),
        migrations.AlterField(
            model_name='autonomo',
            name='ativacao',
            field=models.CharField(blank=True, choices=[('1', 'Inativo'), ('2', 'Ativo')], default='Inativo', max_length=10),
        ),
    ]
