# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0010_auto_20161013_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='id_em',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canal_corretor.Empreendimento'),
        ),
    ]
