# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-13 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0010_auto_20170113_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='imob',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='afiliado', serialize=False, to='canal_corretor.Imobiliaria'),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empreendimento', to='canal_corretor.Categoria', verbose_name='categoria'),
        ),
    ]
