# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0011_auto_20161013_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='id_em',
        ),
        migrations.AddField(
            model_name='material',
            name='emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='canal_corretor.Empreendimento'),
        ),
    ]
