# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-26 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0012_auto_20161026_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='corretor',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação'),
        ),
        migrations.AddField(
            model_name='corretorafiliado',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação'),
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação'),
        ),
    ]
