# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0012_auto_20161013_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canal_corretor.Empreendimento'),
        ),
    ]
