# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-28 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0013_auto_20161026_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretorafiliado',
            name='vinculado',
            field=models.ForeignKey(blank='False', on_delete=django.db.models.deletion.CASCADE, to='canal_corretor.Imobiliaria', verbose_name='Imobiliária vinculada'),
        ),
    ]
