# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0013_auto_20161013_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='emp',
            new_name='emreendimento',
        ),
    ]
