# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-28 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0014_auto_20161028_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corretorafiliado',
            name='vinculado',
        ),
    ]
