# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0015_remove_corretorafiliado_vinculado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/img', verbose_name='Insira uma imagem'),
        ),
    ]
