# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0017_auto_20161101_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Insira uma imagem:'),
        ),
    ]
