# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-03 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0020_auto_20161103_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='img',
            field=models.ImageField(blank=True, upload_to='canal_corretor/static/img', verbose_name='Insira uma imagem:'),
        ),
    ]
