# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-03 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0021_auto_20161103_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='img',
            field=models.ImageField(blank=True, upload_to='canal_corretor/static/img', verbose_name='Insira uma imagem'),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='img',
            field=models.ImageField(blank=True, upload_to='/static/img', verbose_name='Insira uma imagem:'),
        ),
    ]
