# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0023_auto_20161103_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='status',
            field=models.CharField(choices=[('1', 'Pronto para Construir'), ('2', 'Em breve'), ('3', 'Lançado')], default=False, max_length=30, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
