# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0034_auto_20161104_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/img/ep', verbose_name='Insira uma imagem:'),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/img/imob', verbose_name='Insira uma imagem:'),
        ),
        migrations.AlterField(
            model_name='material',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/img/mt', verbose_name='Insira uma imagem'),
        ),
    ]
