# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-07 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0036_empreendimento_sub_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do arquivo')),
                ('img', models.ImageField(blank=True, upload_to='static/img/mt', verbose_name='Insira uma imagem')),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canal_corretor.Empreendimento')),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do arquivo')),
                ('file', models.FileField(blank=True, upload_to='static/doc', verbose_name='Arquivos ')),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canal_corretor.Empreendimento')),
            ],
        ),
        migrations.CreateModel(
            name='Tabela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do arquivo')),
                ('file', models.FileField(blank=True, upload_to='static/doc', verbose_name='Arquivos ')),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canal_corretor.Empreendimento')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do arquivo')),
                ('img', models.ImageField(blank=True, upload_to='static/img/vd', verbose_name='Insira uma imagem')),
                ('link', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material de apoio'},
        ),
        migrations.RemoveField(
            model_name='material',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='material',
            name='file',
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('São Paulo', 'SP'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=100, verbose_name='Estado*:'),
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='resp',
            field=models.CharField(max_length=150, verbose_name='Corretor Resposável*:'),
        ),
        migrations.AlterField(
            model_name='material',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/img/ma', verbose_name='Insira uma imagem'),
        ),
        migrations.AlterField(
            model_name='material',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do arquivo'),
        ),
    ]
