# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-07 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canal_corretor', '0037_auto_20161107_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corretor',
            options={'verbose_name': 'Corretor'},
        ),
    ]
