# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corretor',
            name='cidade',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
