# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canal', '0003_empreendimento_id_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='id_cat',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.SET_DEFAULT, to='canal.Categoria'),
        ),
    ]
