# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canal', '0004_auto_20161013_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='id_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canal.Categoria'),
        ),
    ]
