# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canal', '0005_auto_20161013_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empreendimento',
            name='id_cat',
        ),
    ]
