# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal', '0006_remove_empreendimento_id_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='lancamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data prevista para lançamento'),
        ),
    ]
